### ISSUE TITLE
Unlinked tokens don't process fully

### ISSUE THREAD

**Issue by Sebmaster777** [websterguy/pf1-mighty-morphin-mod#28]
No buffs are being applied to the creature

**Comment by websterguy** [comment]
Cannot reproduce using latest versions of foundry, pf1, and mod with latest version of macros from mod. Can you provide more info?

**Comment by Sebmaster777** [comment]
Ok, I figured out what was happening. So when using this on an unlinked token, it seems to apply the changes to the original sheet in the directory rather than applying it to the sheet on the scene. It seems this is only an issue with beast shape, Elemental body and Plant shape

**Comment by websterguy** [comment]
Ah, yes, unlinked tokens are an issue. I haven't really put in anything for handling them.

⁣Get BlueMail for Android ​
