### ISSUE TITLE
Armorcheck Penalty is still applied to character even if armor has wild armor property

### ISSUE THREAD

**Issue by McGreger** [websterguy/pf1-mighty-morphin-mod#35]
A creature wearing a wild enchanted armor should not keep the armor check penalty of the armor. 
It would be nice to add Armor Check Penalty correction value via changes tab in wild shape buff.

**Comment by websterguy** [comment]
https://paizo.com/paizo/faq/v5748nruor1fm#v5748eaic9tl1

> If you do gain any benefits (as with the wild property), then you do suffer the armor check penalty, movement speed reduction, and arcane spell failure chance.
