### ISSUE TITLE
Feature Request: Add fillable field to add amulet of mighty fists bonus automatically to natural attacks

### ISSUE THREAD

**Issue by Sebmaster777** [websterguy/pf1-mighty-morphin-mod#8]

**Comment by websterguy** [comment]
How about if instead I look to see if the actor has an item with "Amulet of Mighty Fists" in the name, then look for a "+X" within that name and automatically add an enhancement bonus of X to the natural attacks?

**Comment by Sebmaster777** [comment]
That would probably be better, yeah

**Comment by eXaminator** [comment]
This doesn't seem to work for me. It doesn't recognize the Amulet Of Might Fists +1. It makes no difference if I have it equipped or not, I get the same slam bonus (without the enhancement bonus).

I even ran the following code and it returned the correct bonus, but it just doesn't get applied:
```
/\+(\d+)/.exec(game.actors.get('QnrZ8011xA2NaXiD').items.find(o => o.name.toLowerCase().includes('amulet of mighty fists') && o.data.data.equipped)?.name)[1]
```
The returned bonus is a string, maybe it needs to be converted to a number?

**Comment by websterguy** [comment]
It is working fine for me. With an Amulet of Mighty Fists +1, the enhancement bonus of 1 is added straight to the natural attack as shown here.
![image](https://user-images.githubusercontent.com/54455090/170122766-2809081f-43a9-4d8b-b3ba-ffa9da3c0dd8.png)
